### ISSUE TITLE
Possibility of opening up Jellyfin Rewind early this year

### ISSUE THREAD

**Issue by StayBlue** [Chaphasilor/jellyfin-rewind#4]
Hello,
I love the contributions you have made to the Jellyfin ecosystem! This year, Spotify opened up Spotify wrapped earlier than I expected (today, as of the time of posting). Could Jellyfin Rewind open early as well? I'm sorry if this is a bother.

**Comment by Chaphasilor** [comment]
Hey! Thanks for the kind words :)

I assumed Wrapped would lauch on the 30th, but I guess they're a day early.  
Either way, I actually haven't started working on JF Rewind at all yet, that is planned for December. I just didn't find the time for it so far because I was busy with Finamp.

And there are certain improvements that I would really like to make for this year, so I'll stick with December 31st for now. Hope you understand.  
Also, because Jellyfin's playback reporting and internal stats aren't super reliable or detailed, it's actually best to have a full year between generating reports.

That being said, there is nothing stopping you from going to the releass page and downloading the 2022 version for self-hosting. You might have to change a variable though, not sure (I'm on mobile right now).  
Just keep in mind that the Jellyfin-based stats (without the Playback Reporting plugin) will contain all data from previous years.

**Comment by Chaphasilor** [comment]
So here's last year's version but with a target year of 2023 instead of 2022. Haven't tested it, but it should work just fine :)  

[JF-Rewind_2022-version-but-for-2023.zip](https://github.com/Chaphasilor/jellyfin-rewind/files/13506589/JF-Rewind_2022-version-but-for-2023.zip)  
Just make sure you're not saving the rewind report generated by this version, because you won't be able to use it with the actual 2023 version...

**Comment by StayBlue** [comment]
> So here's last year's version but with a target year of 2023 instead of 2022. Haven't tested it, but it should work just fine :) [JF-Rewind_2022-version-but-for-2023.zip](https://github.com/Chaphasilor/jellyfin-rewind/files/13506589/JF-Rewind_2022-version-but-for-2023.zip)
> 
> Just make sure you're not saving the rewind report generated by this version, because you won't be able to use it with the actual version for 2023...

You're the best! I'll try it out later. Thank you!

**Comment by Chaphasilor** [comment]
Did it work? :)

**Comment by StayBlue** [comment]
> Did it work? :)

Just tried it out and it doesn't seem to work.
![image](https://github.com/Chaphasilor/jellyfin-rewind/assets/23127866/de200395-21eb-430a-9f5f-63db3ec967d1)

There are no styles and the buttons don't seem to do anything. I'll try tweaking around with it and seeing if I can get it working.

**Comment by Chaphasilor** [comment]
Hah, right, sorry about that. You definitely need to use a web server instead of opening the `index.html` directly, but it looks like you figured that out.

As for the other issue, try replacing the `#start` at the end of the URL with a `#server`, then it should work. If not, I'll upload another custom build tomorrow :)  
It's been a year since I've looked at the code, so bear with me...

**Comment by StayBlue** [comment]
> Hah, right, sorry about that. You definitely need to use a web server instead of opening the `index.html` directly, but it looks like you figured that out.
> 
> As for the other issue, try replacing the `#start` at the end of the URL with a `#server`, then it should work. If not, I'll upload another custom build tomorrow :) It's been a year since I've looked at the code, so bear with me...

After replacing `#start` with `#server`, I can input my server's address here:
![image](https://github.com/Chaphasilor/jellyfin-rewind/assets/23127866/7733d665-b616-4131-ad4f-f62c59380ccb)

However, all this does is redirect me to the playback reporting plugins page on my server.

**Comment by Chaphasilor** [comment]
Okay, this one I tested:

[JF-rewind_2022-but-for-2023.zip](https://github.com/Chaphasilor/jellyfin-rewind/files/13536139/JF-rewind_2022-but-for-2023.zip)

I also set the Playback Reporting plugin as the default data source, because that is the only way to get stats for this year only and not 2022 as well. You can change it in the settings :)

**Comment by Chaphasilor** [comment]
Ahh, damn it. I did put in a disclaimer about this last year, but I guess it wasn't obvious enough. I'll add a big button this year that can install and configure the plugin with just a tap, hopefully that solves such issues...  

Do you still have last year's report? If yes, you will be able to use Jellyfin's built-in stats, because I can simply subtract last year's values from this year's values to get the data only for this year 😁
